#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : alsa-plugins
Version  : 1.1.5
Release  : 11
URL      : ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.5.tar.bz2
Source0  : ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.5.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: alsa-plugins-lib
Requires: alsa-plugins-data
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(sndfile)

%description
Arcam AV Amplifier ALSA Control plugin
======================================
This plugin exposes the controls for an Arcam AV amplifier
(see: http://www.arcam.co.uk/) as an ALSA mixer device.

%package data
Summary: data components for the alsa-plugins package.
Group: Data

%description data
data components for the alsa-plugins package.


%package lib
Summary: lib components for the alsa-plugins package.
Group: Libraries
Requires: alsa-plugins-data

%description lib
lib components for the alsa-plugins package.


%prep
%setup -q -n alsa-plugins-1.1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510755570
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510755570
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/alsa/alsa.conf.d/50-pulseaudio.conf
/usr/share/alsa/alsa.conf.d/99-pulseaudio-default.conf.example

%files lib
%defattr(-,root,root,-)
/usr/lib64/alsa-lib/libasound_module_conf_pulse.so
/usr/lib64/alsa-lib/libasound_module_ctl_arcam_av.so
/usr/lib64/alsa-lib/libasound_module_ctl_oss.so
/usr/lib64/alsa-lib/libasound_module_ctl_pulse.so
/usr/lib64/alsa-lib/libasound_module_pcm_oss.so
/usr/lib64/alsa-lib/libasound_module_pcm_pulse.so
/usr/lib64/alsa-lib/libasound_module_pcm_upmix.so
/usr/lib64/alsa-lib/libasound_module_pcm_usb_stream.so
/usr/lib64/alsa-lib/libasound_module_pcm_vdownmix.so
/usr/lib64/alsa-lib/libasound_module_rate_samplerate.so
/usr/lib64/alsa-lib/libasound_module_rate_samplerate_best.so
/usr/lib64/alsa-lib/libasound_module_rate_samplerate_linear.so
/usr/lib64/alsa-lib/libasound_module_rate_samplerate_medium.so
/usr/lib64/alsa-lib/libasound_module_rate_samplerate_order.so
/usr/lib64/alsa-lib/libasound_module_rate_speexrate.so
/usr/lib64/alsa-lib/libasound_module_rate_speexrate_best.so
/usr/lib64/alsa-lib/libasound_module_rate_speexrate_medium.so
